### ISSUE TITLE
Format Caption text

### ISSUE THREAD

**Issue by zachesor** [PWesterdale/KirbyGram#11]
Can you tell me what you mean by this: "pass this through the instagram::format_text() function"

I tried to using <?= $image->caption()->instagram::format_text() ?> but that breaks the page.

**Comment by steadweb** [comment]
I think there's a typo within the documentation, the method is called `text_format`, and should be called like so:

```
<?= Instagram::text_format($image->caption()) ?>
```

**Comment by zachesor** [comment]
Yes this is accurate.
