### ISSUE TITLE
feed()->limit(1)

### ISSUE THREAD

**Issue by zachesor** [PWesterdale/KirbyGram#12]
Is there a reason that limiting the return to only 1 image does not work?

My code was:
<? foreach($instagram->feed()->limit(1)->get() as $image): ?>
<img src="<?= $image->max() ?>" width="350" height="350"/>
<? endforeach; ?>

**Comment by steadweb** [comment]
@zachesor are you getting an error? Looks like the code doesn't return an array if you set `limit` to 1, you shouldn't have to iterate the `array` then. 

Try the following instead of using `foreach`:

```
$image = $instagram->feed()->limit(1); // should return an instance of Media
```

**Comment by zachesor** [comment]
No error in the log for this specific line, it just doesn't load. What am I missing?

```
<?php $instagram = new Instagram(); ?>
    <? $image = $instagram->feed()->limit(1); ?>
```

**Comment by steadweb** [comment]
Apologies @zachesor - I forgot to add `->get()` to the chain, try the following:

```
$image = $instagram->feed()->limit(1)->get(); // should return an instance of Media
```

**Comment by zachesor** [comment]
That fixed it. Thank you for the assistance!
