### ISSUE TITLE
created_time question

### ISSUE THREAD

**Issue by zachesor** [PWesterdale/KirbyGram#14]
Does anyone know how to use the created_time function to display the date the image was posted to Instagram? The output of the following code only results in the Unix epoch time of Jan 1, 1970.

```
<? echo date('D M j, Y', $created_time); ?>
```

**Comment by PWesterdale** [comment]
This is referenced in #9 - I've been extremely busy recently but will be aiming to get the latest version with various bug fixes and updates out soon.

**Comment by zachesor** [comment]
No worries. Thanks for your attention.
