### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by rppld** [PWesterdale/KirbyGram#21]
Is there a way to access the different pages of the response? Something along the lines of `$instagram->feed()->page(2)`?

What I'm trying to achieve is loading in the pages (with their respective content) with some sort of "Load more"-functionality.

**Comment by PWesterdale** [comment]
Hi there,

This functionality is not available at the minute - but I may be able to add it in. The repository is due a bit of work and I hope to get round to it soon.

**Comment by rppld** [comment]
Okay, thanks for the quick response. I've used Instafeed.js for now, they have a built-in feature to fetch the next page, maybe that'll help you with your plugin too http://instafeedjs.com
