### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by alordmg** [PWesterdale/KirbyGram#22]
Hello!

Is it possible to reduce the time the images are cached?

Thanks!

**Comment by steadweb** [comment]
@alordmg you can set this yourself within config it seems.

https://getkirby.com/docs/advanced/options

Kirbygram uses the `c` class to get/set config. The default value (within code) is set to 30 minutes. 

https://github.com/PWesterdale/KirbyGram/blob/master/lib/Instagram.php#L73

Within your site's config file, add the following line:

```
c::set('kg.cache_period', '24 hours'); // set the cache for 24 hours
```

**Comment by PWesterdale** [comment]
@steadweb is correct.

However I'd ask you nicely not to lower the cache below two minutes to keep us from hitting any rate limits!

Thanks
