### ISSUE TITLE
Fatal errors on Done page

### ISSUE THREAD

**Issue by jimhare** [PWesterdale/KirbyGram#5]
On the "Done" page after setup, in Kirby's debug mode, I get the following error:

```
Fatal error: Using $this when not in object context in /Users/foo/Sites/bar/site/plugins/kirbygram/lib/Instagram/MediaResponse.php on line 39
```

This error comes right at the bottom of the page, after the **Likes** heading. The images under the **Feed** heading are fetched and displayed fine.

Also, if I try and use the $instagram object in any templates I get this error:

```
Notice: Undefined variable: instagram in /Users/foo/Sites/bar/site/templates/gramtest.php on line 11

Fatal error: Call to a member function feed() on a non-object in /Users/foo/Sites/bar/site/templates/gramtest.php on line 11
```

Not sure if they're related issues. I'm in a local environment and have followed the appropriate instructions.

**Comment by PWesterdale** [comment]
Hi @jimhare,

The second issue can be solved by instantiating instagram above the template output:

<? $instagram = new \Instagram(); ?>

I'll take a look into the first issue, am I right in presuming your account has not 'liked' any images on instagram?

**Comment by luxlogica** [comment]
I also get an error on the 'Done' page - mine appears just under the 'Video' heading:

```
Notice: Undefined offset: 0 in [...]/Site_Final/site/plugins/kirbygram/lib/Instagram/MediaResponse.php on line 48
```

I don't know if it is at all related to the error above, or whether it's something totally different...

**Comment by PWesterdale** [comment]
apologies, didn't get around to debugging this. will check it over tonight.

**Comment by PWesterdale** [comment]
Hi @luxlogica could you please test the fix on the branch bugfix/no-items and let me know if that solves your problem?

**Comment by luxlogica** [comment]
@PWesterdale yes, that fixed it for me - good work!
