### ISSUE TITLE
feed stops at 20 images

### ISSUE THREAD

**Issue by ghost** [PWesterdale/KirbyGram#8]
Hi Paul – nice work. I'm just having a small issue – no matter what i do, the feed stops at 20 images.
$instagram->feed()->limit(25)->get(); 
or $instagram->feed()->limit(989)->get(); 
 only return 20 images (and yes, there's definitely more than that in the account I'm accessing).
$instagram->feed()->only('image')->get(); returns nothing at all.
Any ideas what could be wrong here?
many thanks.

**Comment by PWesterdale** [comment]
Hi @luckystairs 

I fear you may have hit a limitation of my current implementation. Instagram returns a paginated response of images, at current I'm only displaying the first page.

If you would be willing to share your configuration file with me, I can take a look at it this evening for you?

**Comment by ghost** [comment]
Hi Paul – thanks. config at this link: 
https://www.dropbox.com/s/md4ym7p55lseua9/config.json.zip?dl=0
–Duncan

**Comment by PWesterdale** [comment]
Got that dude, you can delete that zip file now.

Will update as soon as I have something

**Comment by ghost** [comment]
Hi – just find a possible solution (almost works for me anyway)
https://instagram.com/developer/endpoints/users/#get_users_media_recent lists various other parameters – adding something like 'count' => 1000 or 'min_timestamp' => 0 into the data array part of the feed function (Instagram.php at about line 85) gets more images – just not the last few...

**Comment by PWesterdale** [comment]
No problem, I'm looking at another approach at the minute - will let you know how it works out.

**Comment by PWesterdale** [comment]
I'm currently working on this. ETA 2 days.

**Comment by PWesterdale** [comment]
This is currently available on master - Please feel free to test, it should be much better with getting as many images as you require. just pass a number to limit (say 100) and it should get them for you.
