### ISSUE TITLE
Request date() and caption()->excerpt()

### ISSUE THREAD

**Issue by timnarr** [PWesterdale/KirbyGram#9]
Hey Paul,

is there a way to get something like date(), wich outputs the date the image was posted?
And I wonder if it's possible to get an excerpt from the caption. 
Like <?php echo $image->caption()->excerpt(100) ?>

Thank you :-)

**Comment by zachesor** [comment]
I would also like to see the date() enhancement.

**Comment by PWesterdale** [comment]
This is currently on master. Please feel free to download a copy and try the new created() function on a media object. It returns a PHP Date Object.
With regards to excerpt you can use the core Kirby excerpt functionality:
http://getkirby.com/docs/toolkit/api/str/excerpt

**Comment by timnarr** [comment]
Hey Paul,

great news :-) but it doesn't work for me. I replaced only the "lib" folder by the your newer one and now I have a blank page. Has anything else changed ? 

Thank you!

**Comment by PWesterdale** [comment]
Can you check your PHP error logs? you should be seeing an error of some sort - Blank screen usually means you will need to check your apache/nginx log.

**Comment by timnarr** [comment]
It's an Internal server Error... and I found out that it is caused by the created() function. 

``` php
<?php $instagram = new Instagram(); ?>
<?php foreach($instagram->feed()->limit(6)->get() as $image): ?>
<div class="item instagramimages">
  <a href="<?php echo $image->link() ?>">
    <img src="<?php echo $image->small() ?>" width="280" height="280" />
    <div class="caption fade-caption">
      <div class="child">
        <span class="captiontxt"><?php echo $image->likes() ?> Likes</span>
      </div>
    </div>
  </a>
  <p>
    <strong><?php echo $image->created() ?></strong>
    <?php echo $image->caption() ?></p>
</div>
<?php endforeach ?>
```

**Comment by PWesterdale** [comment]
Sorry about that @TimGr - please grab the latest commit - it should fix your problem.

`created()` is now `created($format)` so you just need to pass the desired date time format (It falls back to d/m/Y) and you should have the dates you need.

Thanks!

**Comment by timnarr** [comment]
Great. Now it works like a charm :+1: 
Thank you!
